"use client";

import { useState } from "react";
import Link from "next/link";
import { SectionTitle } from "@/components/SectionTitle";

export default function InstallPage() {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({name:"",phone:"",area:"",plan:"Business Pro",notes:""});
  const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
  return <main className="section-shell py-14"><SectionTitle eyebrow="Installation request" title="Capture a complete request the operations team can act on" text="The goal is to replace fragmented phone/WhatsApp intake with a structured workflow." /><div className="mt-10 grid gap-6 md:grid-cols-[1fr_.8fr]"><div className="card p-7">{submitted?<div className="py-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h3 className="mt-5 text-2xl font-black">Request captured</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Demo request ID: <strong>INS-20481</strong>. In production this would create an operations ticket and notify the assigned queue.</p><button className="btn btn-secondary mt-5" onClick={()=>setSubmitted(false)}>Create another</button></div>:<><div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-bold">Full name</label><input className="input mt-2" value={form.name} onChange={e=>update("name",e.target.value)} placeholder="Customer name"/></div><div><label className="text-sm font-bold">Phone</label><input className="input mt-2" value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+229 ..."/></div><div><label className="text-sm font-bold">Service area</label><select className="input mt-2" value={form.area} onChange={e=>update("area",e.target.value)}><option value="">Choose</option>{["Cotonou","Abomey-Calavi","Porto-Novo","Sèmè-Kpodji"].map(a=><option key={a}>{a}</option>)}</select></div><div><label className="text-sm font-bold">Plan</label><select className="input mt-2" value={form.plan} onChange={e=>update("plan",e.target.value)}><option>Home Plus</option><option>Business Pro</option><option>Business Max</option></select></div></div><div className="mt-4"><label className="text-sm font-bold">Installation notes</label><textarea className="input mt-2 min-h-28" value={form.notes} onChange={e=>update("notes",e.target.value)} placeholder="Nearest landmark, preferred time, business requirements…" /></div><button className="btn btn-primary mt-5 w-full" onClick={()=>setSubmitted(true)} disabled={!form.name || !form.phone || !form.area}>Submit installation request</button></>}</div><div className="card p-7"><div className="pill">Operations handoff</div><h3 className="mt-5 text-xl font-black">What the ISP team receives</h3><ul className="mt-5 space-y-3 text-sm text-slate-600"><li>✓ Customer identity and contact</li><li>✓ Exact service area</li><li>✓ Requested package</li><li>✓ Installation notes</li><li>✓ Request timestamp / tracking ID</li><li>✓ Assignment to support or field operations</li></ul><Link href="/support" className="btn btn-secondary mt-7 w-full">See support workflow</Link></div></div></main>;
}
